# Collector specific configuration
url: "https://api.adam.geospatial.wfp.org/api/collections"

event_types:
  SM:
    collection_id: "adam.adam_eq_events"
    event_type: "SM"
    tag: "earthquake"
    name: "{event['iso3']}-earthquake-{event['uid']}"
    title: "{event['iso3']}: Earthquake - {event['mag']}M - {parse_date(event['published_at']).strftime('%b %Y')}"
    description: >-
      Magnitude {event['mag']} earthquake at {event['depth']} depth occurred on {parse_date(event['published_at']).strftime('%b %d %Y')} {event['place']}.
      The epicentre of the earthquake was located at latitude {event['latitude']} longitude {event['longitude']}.
      It impacted {event['pop_est_buff_3']} people within {event['dist_km_buff_3']}km.
  TS:
    collection_id: "adam.adam_ts_events"
    event_type: "TS"
    tag: "tropical storm"
    name: "{event['iso3']}-cyclone-{event['event_id']}"
    title: "{event['iso3']}: Cyclone - {event['storm_status']} - {parse_date(event['published_at']).strftime('%b %Y')}"
    description: >-
      Cyclone ({event['storm_status'].lower()}) during the period {parse_date(event['from_date']).strftime('%b %d %Y')}-{parse_date(event['to_date']).strftime('%b %d %Y')} in {event['countries']}.
      The center of the storm was located near latitude {event['latitude']} longitude {event['longitude']}.
#  FL:
#    collection_id: "adam.adam_fl_events"
#    event_type: "FL"
#    tag: "flood"
#    name: "{event['iso3']}-cyclone-{event['event_id']}"
#    title: "{event['iso3']}: Cyclone - {event['storm_status']} - {parse_date(event['published_at']).strftime('%b %Y')}"
#    description: >-
#      Cyclone ({event['storm_status'].lower()}) during the period {parse_date(event['from_date']).strftime('%b %d %Y')}-{parse_date(event['to_date']).strftime('%b %d %Y')} in {event['countries']}.
#      The center of the storm was located near latitude {event['latitude']} longitude {event['longitude']}.
